# Generated by Django 4.0.4 on 2022-07-21 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(default='notitle', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 19, 7, 53, 313825, tzinfo=utc)),
        ),
    ]
