# Generated by Django 4.0.4 on 2022-07-21 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_title_alter_poll_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
