# Generated by Django 4.0.4 on 2022-07-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
