# Generated by Django 4.0.4 on 2022-07-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_maximum_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='no name', max_length=128),
            preserve_default=False,
        ),
    ]
